name: UNIT-TESTS-CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
    types: [opened, synchronize, reopened]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ap-southeast-2
  AWS_USER_ID: ${{ secrets.AWS_ACCESS_USER_ID }}

jobs:
  UnitTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: practera-app-v2-1-cache-node-modules
        with:
          path: |
            ~/.npm
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install modules
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: |
          npm install

      - name: Unit tests
        run : |
          test -f src/environments/environment.ts && echo "environment here" || cp src/environments/environment.local.ts src/environments/environment.ts
          ng build
          ng test --karmaConfig=src/karma.conf.sonarci.js --no-watch

      - name: List files
        if: ${{ always() }}
        run: |
          pwd
          ls -a /home/runner/work/practera-app-v2-1/practera-app-v2-1/tests

      - name: SonarCloud Scan
        if: ${{ always() }}
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}